webpack/sass-loader

- CHANGELOG.md
- index.js
- test/prepare.js
- test/sass/import-other-style.sass
- test/scss/import-other-style.scss
> Fix importing css files from sass/scss

- README.md
Add option --save-dev for install instruction.
> Add --save-dev

- README.md
I spent way too long banging my head against my desk unsure of why my page wasn't rendering with source maps. I finally found out that you need to have both a link and a require statement for this to work properly.
> Help avoid common pitfalls

- index.js
> Prevent error when the node-sass error does not contain a file

- README.md
Related: https://github.com/webpack/style-loader/issues/149
> Corrected invocations of raw-loader, style-loader and css-loader

- index.js
- test/index.test.js
> Export instance of node-sass compiler

- package.json
> update webpack peerDependency

- index.js
- test/index.test.js
- Remove unused stuff
- Update code for ES6 features
> Refactor code

- README.md
Both gave a deprecation notice.
> Replace deprecated methods in production example

- README.md
> README: Parse the 1st paragraph's markdown links

- README.md
> Correct gitter badge link

- test/index.test.js
- test/sass/another/variables.sass
- test/sass/language.sass
- test/scss/another/_variables.scss
- test/scss/language.scss
Fixes https://github.com/webpack-contrib/sass-loader/issues/294
> test: add tests for unicode character

- README.md
> docs(readme): Fixes typo in loader description

- lib/loader.js
- package.json
- Increase performance
Reference: https://github.com/webpack/webpack/pull/6470
> perf: use `neo-async` instead `async`

- README.md
Thanks to all the contributors and maintainers for the great package!
http://www.sassnotsass.com/
> Capitalize Sass

- README.md
> Correct implementation in documentation

- package-lock.json
- package.json
> test: upgrade webpack-dev-server (#605)

- package-lock.json
- package.json
> chore: integrate commitlint

- appveyor.yml
Better testing on windows
No
No
> ci: impove appveyor config

- README.md
- lib/loader.js
- test/index.test.js
- test/scss/simple.scss
Load `sass` (when he present in deps)/
No
No
> Feat support dart sass

- README.md
Add sourcemap option to style-loader: https://github.com/webpack-contrib/sass-loader/issues/660
> Add source-map to style-loader

- lib/loader.js
- lib/webpackImporter.js
- package-lock.json
- package.json
avoid unnecessary deps
No
fixes #700 fixes #652
> refactor: avoid `lodash.tail`

- package.json
> fix: relax node engine

- lib/loader.js
fixes #556
Should be no, but if you faced with problem feel free to open new issue
No
> fix: prefer `sass`/`scss`/`css` extensions

- .eslintrc.js
- .gitattributes
- .github/CONTRIBUTING.md
- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
- .nycrc
- .prettierignore
- .prettierrc.js
- .travis.yml
- LICENSE
- README.md
- appveyor.yml
- babel.config.js
- commitlint.config.js
- husky.config.js
- lint-staged.config.js
- package-lock.json
- package.json
- src/formatSassError.js
- src/importsToResolve.js
- src/index.js
- src/normalizeOptions.js
- src/proxyCustomImporters.js
- src/webpackImporter.js
- test/node_modules/another/module.js
update defaults
Only for development environment, you need node@8 for development
No
> chore: `webpack-default` part 2

- src/cjs.js
- src/formatSassError.js
- src/importsToResolve.js
- src/index.js
- src/normalizeOptions.js
- src/proxyCustomImporters.js
- src/webpackImporter.js
- test/__snapshots__/implementation-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/cjs.test.js
- test/helpers/compiler.js
use import/export and some refactor
No
No
> refactor: code

- src/importsToResolve.js
Minor refactor to have a more concise version.
N/A
N/A
> chore(importsToResolve): minor refactor

- package-lock.json
- package.json
- test/__snapshots__/loader.test.js.snap
- test/helpers/getPureCode.js
- test/loader.test.js
- test/sass/bootstrap.sass
- test/scss/bootstrap.scss
ensure what bootstrap@4 works fine
No
No
> test: bootstrap@4

- src/importsToResolve.js
Minor grammatical correction.
N/A
N/A
> fix(importsToResolve): minor grammatical correction

- test/helpers/getCodeFromSass.js
- test/loader.test.js
- test/sass/dir-with-underscore-index/_index.sass
- test/sass/import-alias.sass
- test/scss/dir-with-underscore-index/_index.scss
- test/scss/import-alias.scss
fixes #691
No
Already solved in master, just tests
> test: alias on directory with `_index` file

- README.md
> docs: standardize readme

- package.json
> fix: minimum `node` version in `package.json`

- .eslintrc.js
- azure-pipelines.yml
- babel.config.js
- package-lock.json
- package.json
- src/index.js
Remove support outdated versions
BREAKING CHANGE:
- minimum required `node.js` version is `8.9.0`
- minimum required `webpack` version is `4.36.0`
No
> chore(deps): update

- .prettierrc.js
- package-lock.json
There are two prettier config with same content (config)
No
Removed the `.js` one.
> chore: removed the duplicated prettier config

- package-lock.json
- package.json
- test/helpers/compiler.js
`memory-fs` is deprecated.
N/A
N/A
> chore(deps): switch to memfs

- src/index.js
Making use of `Array.includes()` makes much sense since we're targetting node.js v > 6
N/A
N/A
> refactor: use Array.includes

- package-lock.json
- package.json
- test/helpers/getCompiler.js
Removed redundant new keyword.
Nothing
N/A
> fix(chore): invoke createFsFromVolume as a normal function

- README.md
The current snippet generates the `Invalid configuration object` error.
> fix: broken code snippet

- package-lock.json
- package.json
- test/__snapshots__/validate-options.test.js.snap
Updated `memfs` to the latest release.
Nope
N/A
> chore(deps): update memfs

- test/sourceMap-options.test.js
```js
const compiler = getCompiler(testId, {
devtool: false,
loader: { options },
});
```
Passing in the `devtool` argument would be a good practice for the sake of consistency adhering to the test descriptions.
Nope
N/A
> test: adhere to test descriptions

- test/__snapshots__/sourceMap-options.test.js.snap
- test/sourceMap-options.test.js
Rephrase test descriptions as per the conventions.
Nothing
N/A
> chore: rephrase test descriptions

- src/index.js
- test/__snapshots__/loader.test.js.snap
- test/helpers/getCodeFromSass.js
- test/loader.test.js
- test/node_modules/package-with-style-field-and-css/css/package-with-style-field-and-css.css
- test/node_modules/package-with-style-field-and-css/package.json
- test/node_modules/package-with-style-field-and-css/sass/package-with-style-field-and-css.sass
- test/node_modules/package-with-style-field-and-css/scss/package-with-style-field-and-css.scss
- test/sass/prefer-include-paths.sass
- test/scss/prefer-include-paths.scss
fixes #773
Should be no, but it can break a resolution in very rare cases, but that cases are invalid and should be regarded as a bug
No
> fix: prefer sources from the `includePaths` values

- README.md
- src/getDefaultSassImplementation.js
- test/implementation-option.test.js
- test/validate-options.test.js
Use `sass` (`dart-sass` by default)
Yes
No
> feat: prefer `sass` (`dart-sass`) by default

- .github/workflows/nodejs.yml
- babel.config.js
- package-lock.json
- package.json
BREAKING CHANGE: minimum supported Nodejs version is `10.13`
Drop old node versions
Yes
No
> chore: minimum supported Nodejs version is `10.13`

- package-lock.json
- package.json
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
- test/sass/_foundation-sites-adjusting-css-output-settings.sass
- test/sass/foundation-sites-adjusting-css-output.sass
- test/sass/foundation-sites.sass
- test/scss/_foundation-sites-adjusting-css-output-settings.scss
- test/scss/foundation-sites-adjusting-css-output.scss
- test/scss/foundation-sites.scss
> tests: foundation-sites

- README.md
> docs: options table

- src/getSassOptions.js
Avoid extra unnecessary `includePaths`
Potential yes
No
> fix: resolution logic

- src/getPossibleRequests.js
- src/index.js
- src/webpackImporter.js
- test/__snapshots__/loader.test.js.snap
- test/helpers/getCodeFromSass.js
- test/loader.test.js
- test/sass/process-cwd-with-index-file-inside-directory.sass
- test/scss/process-cwd-with-index-file-inside-directory.scss
Simulate default `sass` behavior
Potential yes
No
> Fix resolution logic

- README.md
Fixed link in documentation for `prependData` (https://webpack.js.org/loaders/sass-loader/#prependdata)
N/A
> Fix link for prependData

- README.md
> docs: yarn pnp + using `dart-sass` by default

- package-lock.json
- package.json
- src/utils.js
Bloated node_modules with ton of packages.
Klona has no dependencies and the package is smaller.
https://packagephobia.com/result?p=klona
https://packagephobia.com/result?p=clone-deep
No
No
> refactor: replace clone-deep with smaller klona

- src/index.js
https://github.com/webpack-contrib/sass-loader/issues/858
No
No
> fix: do not crash on errors

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/helpers/getCodeFromSass.js
- test/loader.test.js
- test/sass/use-material-components-web.sass
- test/scss/use-material-components-web.scss
fixes #872
No
Ref: https://github.com/vercel/next.js/issues/15753
> fix: resolution algorithm

- test/__snapshots__/sourceMap-options.test.js.snap
- test/sourceMap-options.test.js
> test: source maps

- package-lock.json
- package.json
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/helpers/getCodeFromSass.js
- test/loader.test.js
- test/sass/by-dependency.sass
- test/sass/custom-main-files/custom.sass
- test/scss/by-dependency.scss
- test/scss/custom-main-files/custom.scss
> feat: support the `resolve.byDependecy.sass` option

- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
- test/sass/import-circular.sass
- test/sass/use-circular.sass
- test/scss/import-circular.scss
- test/scss/use-circular.scss
> test: circular

- src/utils.js
> fix: crash in custom importers with worker threads

- src/utils.js
- test/loader.test.js
- test/sass/dir-with-css/_name.sass
- test/sass/dir-with-css/name.css
- test/sass/use-dir-with-css.sass
- test/scss/dir-with-css/_name.scss
- test/scss/dir-with-css/name.css
- test/scss/use-dir-with-css.scss
improve logic for resolution
If something stops working this should be considered a bug and please report it.
Refactor logic + small docs about differences
> Refactor resolution logic

- .github/workflows/nodejs.yml
- package-lock.json
Node 10 dropped
Node 10 dropped
No
> chore(deps): node 10 dropped

- babel.config.js
- package.json
something wrong with rebase I done and we lost this
No
No
> fix: `engines`

- README.md
Added sassOptions type and fixes typo
> docs(readme): added sass options

- src/utils.js
- test/__snapshots__/implementation-option.test.js.snap
- test/implementation-option.test.js
test more and small refactor
No
No
> test: more

- README.md
Providing additional example which, in my case, didn't require including any additional packages. Borrowed from https://stackoverflow.com/a/60029923/2969615, appeared to be a widely-used solution.
Only updating documentation. No breaking changes
None
> include file loader method of extracting CSS as separate file in README.md

- src/index.js
fix typo in #1123
for more context please see this issue:
https://github.com/webpack-contrib/sass-loader/issues/1122
No
No
> fix: typo in fix of modern api depedencies (#1123)

- .github/workflows/nodejs.yml
fix problems with node v20, fixes https://github.com/webpack-contrib/sass-loader/pull/1130
No
No
> ci: fix node v20

- README.md
> docs: update readme for the `production` mode and `outputStyle`

- src/utils.js
fixes https://github.com/webpack-contrib/sass-loader/issues/1175
No
No
> fix: compatibility with node-sass@9

- package-lock.json
- package.json
- src/utils.js
- test/manual/src/style.scss
- test/manual/webpack.config.js
fix hook part of https://github.com/webpack-contrib/sass-loader/pull/1195
No
No
> fix: use watchClose hook

- src/utils.js
https://github.com/webpack-contrib/sass-loader/pull/1197#discussion_r1567554278
No
No
> fix: avoid multiple sass compiler creation

- .cspell.json
The commit hooks keep failing about this being an unknown word whenever I try to commit a change to the workflow files 😅 
Not a breaking change
> chore: add `autocrlf` as a known word

- package-lock.json
- package.json
- test/__snapshots__/sourceMap-options.test.js.no-node-sass.snap
- test/__snapshots__/sourceMap-options.test.js.snap
- test/sourceMap-options.test.js
fixes https://github.com/webpack-contrib/sass-loader/issues/962
fixes https://github.com/webpack-contrib/sass-loader/pull/968
No
No
> test: added for asset modules

- src/utils.js
- test/__snapshots__/sassOptions-option.test.js.no-node-sass.snap
- test/__snapshots__/sassOptions-option.test.js.snap
- test/sass/slash-div.sass
- test/sassOptions-option.test.js
- test/scss/slash-div.scss
https://github.com/webpack/webpack/discussions/18775#discussioncomment-10695804
No
No
> fix: error message from sass

- README.md
- src/utils.js
- test/__snapshots__/sourceMap-options.test.js.no-node-sass.snap
- test/__snapshots__/sourceMap-options.test.js.snap
For better debug and we did the same for old api
No
No
> fix: include sources content for modern api by default

- src/utils.js
- test/helpers/getCodeFromSass.js
- test/loader.test.js
- test/sass/use-css.sass
- test/sass/use-with-extension.sass
- test/scss/use-css.scss
- test/scss/use-with-extension.scss
> fix: allow to import CSS using `@use` with `css` extension

- .github/workflows/nodejs.yml
- README.md
- package.json
Migrating old structure to new
N/A
https://github.com/webpack/webpack.js.org/pull/7664
> chore: move from master to main branch

- .github/workflows/nodejs.yml
- README.md
- package.json
> chore: move from master to main branch (#1273)
