index.js, package.json, test/prepare.js
I ran into some [issues](https://github.com/interactivethings/catalyst/issues/3) with advanced SASS features, which could be fixed by upgrading node-sass to `v2.0.0-beta`. v2 also has some nice features like a list of included files which can directly be used to mark dependencies, and more accurate errors.
A couple of things I'm not really sure about:
- Dependencies also have been marked when an error occurred. I removed this, since I don't think it's needed (and node-sass doesn't include a file list on error) but I couldn't really find any documentation for it.
- I noticed the tests don't really seem to test the loader but just node-sass.
I've bumped the version to `0.4.0-beta.1`, to indicate that we're still relying on the node-sass beta.
=> Upgrade node-sass to v2

README.md
It was unclear how to `require(something.sass)` (had to search through  `test` : https://github.com/jtangelder/sass-loader/blob/51485cd5245d001dce8c575a0c408c59969fbc67/test/index.test.js#L26 )
This commit clarifies it in the README.
=> Makes it clear how to require .sass

index.js
Since a source map like `{}` is not a valid source map. This causes webpack builds to fail with `Error: "version" is a required argument.`.
This should fix passy/autoprefixer-loader/issues/17.
=> Delete `result.map` when result.map is empty

index.js, package.json
There was some breaking changes in the upcoming 3.0.0 of `node-sass`. This upgrade is needed to run `iojs-1.5.1`.
=> updated node-sass to 3.0.0-pre

index.js
We are using bootstrap-sass (which has `.scss` files) but all our CSS is written in `.sass`.
In version 0.4.2 this worked without a problem. But newer versions of sass-loader add the extension to the file automatically based on configuration (`indentedSyntax`). That means this does not work:
```sass
// app.sass
@import node_modules/bootstrap-sass/assets/stylesheets/bootstrap/variables.scss
```
Currently the loader tries to load file `node_modules/bootstrap-sass/assets/stylesheets/bootstrap/variables.scss.sass`.
With this simple change we introduce "inheritance" of the extension. That means if we import a file with explicit extension all files imported from it will inherit its extension even when there is none specified in the import statement.
Otherwise the behavior remains unchanged. …
=> Fix importing of .sass files from .scss and vice versa

README.md, index.js, test/another/sass/_underscoreIncPathStyle.sass, test/another/sass/incPathsStyle.sass, test/another/scss/_underscoreIncPathStyle.scss, test/another/scss/incPathsStyle.scss, test/index.test.js, test/prepare.js, test/sass/import-include-paths.sass, test/scss/import-include-paths.scss
can not import modules locates at **includePaths" option.
when webpack resolver fails to resolve modules, pass import as-is to node-sass instead of import as-is prefixed with underscore. 
Thus the loader can resolve modules using webpack resolver and from libsass includePaths.
see issue #110  #98  for more details.
=> can not import module which locates at includePaths directories

index.js
Small change discussed in issue #81. Making the change indeed fixes source mapping so I thought I'd create this pull request.
=> Fix for issue #81 - sourceMappingUrl is wrong.

index.js, package.json
Should fix #100 and #119 but this needs testing.
=> Introduce a queue such that a Node thread is available for fs tasks

index.js
This fixes bug where webpack ignores the incremental build and recompile all files in project (win 8.1)
=> Normalize paths of dependencies

README.md
Refer #144.
Struggled to describe the problem clearly. So please feel free to comment.
=> Refer to `resolve-url-loader` as a solution to url rewriting deficit

index.js
Since version 3.0.0 node-sass supports custom functions, so it's gonna be great to use it with sass-loader
=> functions option support

index.js
This allows for [custom importers](https://github.com/sass/node-sass#importer--v200---experimental) to be passed in the loader query.
For example, [node-sass-json-importer](https://github.com/Updater/node-sass-json-importer) could be enabled like so:
```javascript
{
test: /\.scss$/,
loaders: [
"style", 
"css", 
"sass?" + JSON.stringify({
importer: require.resolve('node-sass-json-importer')
});
]
}
```
The above example also resolves #111.
Was hoping to write a test for this, but it seems a bit difficult to fit into the well structured but somewhat rigid test setup. Let me know what you think.
=> Allow `node-sass` importers to be passed in options.

index.js, test/index.test.js
@jtangelder I noticed the merging of config here didn't match the comment. This fixes it and adds a test. There wasn't a similar kind of test so... this is probably not how you'd write the test, but the new test *does* fail without the change to `index.js`.
=> Fix loader query not overriding webpack config

index.js
Instead of requiring loader config to set `sass?indentedSyntax` to compile whitespace significant Sass files, this change will automatically set it for you if necessary (when the current file is a SASS file).
This should make loader config a bit easier, because now you won’t need to have separate loaders for SCSS And SASS. For example:
```javascript
loaders = [{
test: /\.scss$/,
loader: ExtractTextPlugin.extract("style","css!sass")
}, {
test: /\.sass$/,
loader: ExtractTextPlugin.extract("style","css!sass?indentedSyntax")
}]
// BECOMES
loaders = [{
test: /\.(scss|sass)$/,
loader: ExtractTextPlugin.extract("style","css!sass")
}]
```
Additionally this has the side benefit of enabling SCSS <-> SASS interop in some advanced cases. Without this, it wasn’t possible for my …
=> Make the `indentedSyntax` option a bit smarter.

index.js
It's a very rare use case, but wanted to create a PR to find out if it's worthwhile making it to `sass-loader` too.
* I used the `sassOptions.data` key to inject some dynamic Sass variables
* `node-sass` itself allows `data` to be passed in `sassOptions`
But...
`sass-loader` overwrites `sassOptions.data` which means I can't do the variable injection any more.
Check if `sassOptions.data` is present first, and if yes, then prepend that before file content. Otherwise, just roll with the file content as normal.
=> Allow `data` to be passed as sass option

index.js
There are currently two problems regarding source maps file path with this loader:
1. The loader depends on `self.options.output.path` to be set. If you don't set this property the relative urls in line 281 is calculated wrong. By using the context this problem does not exist anymore.
2. node-sass uses the directory in which the map file is created as root path. All source paths within the map are relative to this path. However, when webpack processes the sourcemaps it expects all paths to be relative to the webpack execution directory. To resolve all files correctly I added the `sourceRoot` property to express the relative path.
In combination with the suggested fix for the css-loader (https://github.com/webpack/css-loader/issues/280) this produces nice paths for source maps, that …
=> Fix file path in source maps

index.js, test/tools/customImporter.js
@jhnns, this should fix custom sass importers by passing `resourcePath` instead of `stdin` into the `prev` argument.
Fixes #234
=> Use resoucePath for custom importers

index.js, test/tools/customImporter.js
This is a regression that was introduced with fd6be1f143a1810f7e5072a865b3d8675ba1b94e
#275 #277
=> Fix wrong context in customImporters

package.json
This shouldn't be breaking according to the [release notes](https://github.com/sass/node-sass/releases/tag/v4.0.0)
=> Update node-sass to 4.0.0

index.js, test/index.test.js
Reverts jtangelder/sass-loader#317
This change is not necessary since we're using `peerDependencies`. The user is able to obtain the exact same instance via `require("node-sass")` anyway.
=> Revert "Export instance of node-sass compiler"

index.js, package.json, test/index.test.js
See https://github.com/jtangelder/sass-loader/issues/333
=> Remove synchronous compilation support

lib/normalizeOptions.js, test/index.test.js, test/scss/multipleCompilations/a.scss, test/scss/multipleCompilations/b.scss, test/scss/multipleCompilations/c.scss, test/scss/multipleCompilations/d.scss, test/scss/multipleCompilations/e.scss, test/scss/multipleCompilations/f.scss, test/scss/multipleCompilations/g.scss, test/scss/multipleCompilations/h.scss
=> Fix bug where multiple compilations interfered with each other

lib/loader.js, package.json, test/index.test.js, test/scss/imports.scss, test/sourceMap/entry.js, test/sourceMap/index.html, test/sourceMap/webpack.config.js
- Make all source map paths relative to the entry file. This way we don't have to read the `context` option from the webpack config.
- Fix source maps on Windows: node-sass returns POSIX paths, that's why we need to transform them back to native paths. This fixes an error on windows where the source-map module cannot resolve the source maps.
See https://github.com/jtangelder/sass-loader/issues/366#issuecomment-279460722
=> Improve source map support

lib/loader.js, lib/normalizeOptions.js, test/bootstrapSass/webpack.config.js, test/index.test.js, test/tools/testLoader.js
All source map paths will be relative to process.cwd() from now on.
This removes also the last dependency on this.options.context.
node-sass source map options like sourceMapRoot, omitSourceMapUrl, sourceMapContents are now overridable.
https://github.com/jtangelder/sass-loader/pull/374#issuecomment-279572238
=> Fix incorrect source maps in certain cwds

test/index.test.js
Prevents regressions like https://github.com/webpack-contrib/sass-loader/pull/395
https://github.com/webpack-contrib/sass-loader/issues/21
=> Add tests for empty files

lib/importsToResolve.js, test/index.test.js, test/node_modules/@org/pkg/index.scss, test/node_modules/@org/pkg/package.json, test/sass/import-from-npm-org-pkg.sass, test/scss/import-from-npm-org-pkg.scss, test/tools/createSpec.js
=> fix: resolving of scoped npm packages

README.md
I think the bootstrap path in the documentation is wrong  according to the current bootstrap folder structure(https://cl.ly/1j1W3C0l3z2N) the right path would be `bootstrap/dist/css/bootstrap`
=> change bootstrap path in documentation

lib/importsToResolve.js, test/node_modules/@org/bar/_foo.scss, test/sass/import-from-npm-org-pkg.sass, test/scss/import-from-npm-org-pkg.scss, test/tools/createSpec.js
pr #447 introduce an issue with direct import from scoped npm packages, preventing sass-loader from formatting imported file correctly (see https://github.com/webpack-contrib/sass-loader/pull/447#issuecomment-300263537). This pr indented to fix the issue.
=> fix: importing file directly from scoped npm package

lib/loader.js
Webpack 2 always cacheable all loaders by default.
Ref: https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L36
=> refactor: remove `this.cacheable`

.travis.yml, README.md, appveyor.yml, package.json
- Updates peerDependencies to allow use with Webpack 3.x
- Adds defaults travis & appveyor builds
Closes #471
=> chore: Build and package updates to allow use of webpack3

package.json
Just update `clone-deep` package to latest version. Seems don't have breaking changes.
=> chore(package): update `clone-deep` v0.3.1...2.0.1

README.md
resolve-url-loader should be placed before the sass-loader . Otherwise it is not work for me!
webpack@3.10.0
webpack-dev-server@2.9.7
sass-loader@4.1.1
=> docs(README): rephrase `resolve-url-loader` note

README.md
When running the examples in the code an error is thrown that `style-loader` and `css-loader` are missing.
=> docs(README): add example install instructions for dependencies

lib/loader.js, test/index.test.js
This addresses #561 
This provides the full error instead of:
``sass-loader` requires `node-sass` >=4. Please install a compatible version.``.
When I had the wrong node-sass binding for my version of Linux I get the following with this PR:
```
Module build failed: Error: Missing binding /node_modules/node-sass/vendor/linux-x64-51/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x
```
Which directed me to the actual problem.
=> Report error to user for problems loading node-sass

test/index.test.js, test/node_modules/another/module.js, test/node_modules/another/module.scss, test/scss/another/module.js, test/scss/imports.scss
Additional test cases to ensure that `js` files do not take precedence over `scss` files when the webpack resolver is used. Based on https://github.com/webpack-contrib/sass-loader/pull/558
=> Add test cases to ensure that js files do not take precedence

README.md
Fixes webpack/webpack.js.org#2064
=> update(readme) Use mini-css-extract-plugin in examples.

lib/loader.js, test/index.test.js
The current try/catch is not very helpful. I think it's more helpful to just let the error bubble up.
Fixes #563
Supersedes #575
=> fix: Errors being swallowed when trying to load node-sass

lib/importsToResolve.js, test/index.test.js, test/node_modules/module, test/node_modules/other-module, test/sass/imports.sass, test/scss/imports.scss
Fixes #566
Supersedes https://github.com/webpack-contrib/sass-loader/pull/577
=> fix: Bare imports not working sometimes

package-lock.json, package.json
Integrate lint staged
No
Part of `default`.
=> chore: integrate lint-staged

lib/loader.js, test/index.test.js, test/node_modules/sass-sass-field/nested/style.sass, test/node_modules/sass-sass-field/package.json, test/node_modules/scss-sass-field/nested/style.scss, test/node_modules/scss-sass-field/package.json, test/sass/import-sass-field.sass, test/scss/import-sass-field.scss, test/tools/createSpec.js
Support `sass` field in `package.json`.
No
No
=> feat: support `sass` field in `package.json`

README.md, lib/normalizeOptions.js, test/index.test.js
=> feat: support `data` as `Function`

test/index.test.js, test/node_modules/sass-package-with-index/index.sass, test/node_modules/scss-package-with-index/index.scss, test/sass/import-index.sass, test/scss/import-index.scss, test/tools/createSpec.js
Ensure we support import from package where `index.scss` present.
fixes #535
No
Looks we already support this since `7` version, just add tests
=> test: support import index file from package

lib/normalizeOptions.js, test/index.test.js
This PR adds support for supplying the `functions` option as a function of the [Loader Context](https://webpack.js.org/api/loaders/#the-loader-context). This corresponds to part of [the issue I filed here](https://github.com/webpack-contrib/sass-loader/issues/650).
None. Added a test similar to the one for the "`data` as function"; it passes.
=> Allow passing `functions` option as function

lib/loader.js
Solves issue #671, which breaks the use of resolve-url-loader
None
This will look for "stdin" in the list of sources and replace it with the Sass file. If it can't find the string for whatever reason, it will ~~fall back to the previous functionality and just use the 0th index~~ not do anything.
fixes #671
=> Use the index of stdin instead of zero

lib/loader.js, test/index.test.js, test/node_modules/sass-custom-sass-field/nested/style.sass, test/node_modules/sass-custom-sass-field/package.json, test/node_modules/sass-main-field/nested/style.sass, test/node_modules/sass-main-field/package.json, test/node_modules/sass-style-field/nested/style.sass, test/node_modules/sass-style-field/package.json, test/node_modules/scss-custom-sass-field/nested/style.scss, test/node_modules/scss-custom-sass-field/package.json, test/node_modules/scss-main-field/nested/style.scss, test/node_modules/scss-main-field/package.json, test/node_modules/scss-style-field/nested/style.scss, test/node_modules/scss-style-field/package.json, test/sass/import-custom-sass-field.sass, test/sass/import-main-field.sass, test/sass/import-style-field.sass, test/scss/import-custom-sass-field.scss, test/scss/import-main-field.scss, test/scss/import-style-field.scss, test/tools/createSpec.js
=> feat: allow customize `mainFields` and `extensions`

src/getSassOptions.js, test/__snapshots__/loader.test.js.snap, test/helpers/compiler.js, test/loader.test.js
This bug was introduced when we migrate on webpack@4, works fine for webpack@3
No
No
=> fix: use "compressed" output when mode is "production"

test/helpers/getCodeFromBundle.js, test/helpers/getCodeFromSass.js, test/helpers/index.js, test/helpers/testLoader.js, test/implementation-option.test.js, test/loader.test.js, test/sourceMap-options.test.js
=> refactor: code

src/importsToResolve.js, test/helpers/getCodeFromSass.js, test/sass/import-alias.sass, test/scss/import-alias.scss
=> fix: handle module import ending `/` as module

README.md, src/index.js, test/__snapshots__/webpackImporter-options.test.js.snap, test/webpackImporter-options.test.js
Allow to disable webpack importer
No
fixes #682
=> feat: `webpackImporter` option

README.md, src/getSassOptions.js, test/__snapshots__/loader.test.js.snap, test/__snapshots__/prependData-option.test.js.snap, test/helpers/getCodeFromSass.js, test/loader.test.js, test/prependData-option.test.js
Avoid misleading between `data` option for `sass` and prepend data option for `sass-loader`
BREAKING CHANGE: the `data` option was renamed to the `prependData` option
No
=> refactor: the `data` option was renamed to the `prependData` option

README.md, package-lock.json, package.json, src/getSassOptions.js, src/index.js, src/options.json, test/__snapshots__/validate-options.test.js.snap, test/validate-options.test.js
validate options
Potential, if you have unknown options for loader
No
=> Feat validate options

test/__snapshots__/sassOptions-option.test.js.snap, test/helpers/getCodeFromSass.js, test/sassOptions-option.test.js
=> test: more

README.md, package-lock.json, package.json, test/__snapshots__/sassOptions-option.test.js.snap, test/sassOptions-option.test.js, test/validate-options.test.js
=> Test fiber option

src/options.json, test/__snapshots__/validate-options.test.js.snap, test/validate-options.test.js
Improve option validation
Yes, if you use invalid option before
No
=> Refactor improve implementations validation

README.md, src/getSassOptions.js, src/index.js, test/__snapshots__/sourceMap-options.test.js.snap, test/sourceMap-options.test.js
For better integration with webpack now we respect `devtool` option. If you enable source map (for example using `source-map`) it is enable source map generation, if you use `false`/`eval` value source map generation is disabled.
Same logic should be used for css-loader and other loader which potentially generate source map. It is steps for zre configurations
Yes, if you don't setup `sourceMap` option for loader, and use `devtool` option with any value except `false`/`eval`, source map will be generated and vice versa.
No
=> feat: source map generation depends on the `devtool` option

test/__snapshots__/sassOptions-option.test.js.snap, test/sassOptions-option.test.js
=> Test fix fiber test

README.md, src/getSassOptions.js, src/index.js, test/__snapshots__/sassOptions-option.test.js.snap, test/implementation-option.test.js, test/loader.test.js, test/prependData-option.test.js, test/sassOptions-option.test.js, test/sourceMap-options.test.js, test/validate-options.test.js, test/webpackImporter-options.test.js
automatically uses fibers package if it is available
No
No
=> Feat automatically uses fibers package if it is available

README.md
This PR tries to make the README a more pleasant read.
* Added `YARN` setup
* Webpack as proper nount
* `sass-loader` whenever it is used
* Some small fixes with good intentions
=> docs: overhaul readme

CHANGELOG.md, README.md
This PR is intended to improve the breaking changes coming with version 8.0.0 regarding the option `outputStyle`
=> Improved documentation after breaking changes in release version 8.0.0

src/index.js, src/webpackImporter.js, test/__snapshots__/loader.test.js.snap, test/helpers/getCodeFromSass.js, test/loader.test.js, test/node_modules/package-with-style-field-and-css/package.json
fix: resolution logic when the `includePaths` option used
Potential yes, but in very rare cases because
No
=> fix: resolution logic when the `includePaths` option used

src/getPossibleRequests.js, test/__snapshots__/loader.test.js.snap, test/loader.test.js, test/sass/__file.sass, test/sass/import-underscore-file.sass, test/scss/__file.scss, test/scss/import-underscore-file.scss
=> fix: resolution logic

.github/workflows/nodejs.yml, src/getSassOptions.js, test/__snapshots__/prependData-option.test.js.snap, test/helpers/getCodeFromSass.js, test/prependData-option.test.js
Avoid difference `[contenthash]` on difference os
No
No
=> fix: avoid different content on different os

test/__snapshots__/validate-options.test.js.snap, test/validate-options.test.js
=> test: refactor

src/getSassOptions.js, test/__snapshots__/loader.test.js.snap, test/loader.test.js, test/sass/sass_path-env.sass, test/sass/sass_path/file.sass, test/sass/sass_path_other/other.sass, test/scss/sass_path-env.scss, test/scss/sass_path/file.scss, test/scss/sass_path_other/other.scss
support resolution from `SASS_PATH`
In theory can be in some rare cases
No
=> feat: support SASS-PATH env variable

src/getSassOptions.js, test/__snapshots__/loader.test.js.snap, test/loader.test.js, test/sass/process-cwd.sass, test/sass/simple.sass, test/scss/process-cwd.scss
Support resolution from `process.cwd()` (like do `sass`)
Potential yes
No
=> feat: support `process.cwd()` resolution

src/getPossibleRequests.js, src/webpackImporter.js, test/__snapshots__/loader.test.js.snap, test/helpers/getCodeFromSass.js, test/loader.test.js, test/node_modules/package-with-index/_index.scss, test/sass/import-prefer-main-files-with-extension.sass, test/scss/import-prefer-main-files-with-extension.scss
=> test: resolution logic

src/index.js, src/utils.js, test/__snapshots__/loader.test.js.snap, test/helpers/getCodeFromSass.js, test/loader.test.js, test/node_modules/package-with-same-import/package.json, test/node_modules/package-with-same-import/style.scss, test/node_modules/package-with-same-import/test/scss/package-with-package.scss, test/sass/package-with-package.sass, test/sass/package-with-same-import.sass, test/scss/package-with-package.scss, test/scss/package-with-same-import.scss
fixes #863
No
Inside the comment in the source code
=> fix: resolution algorithm for `node-sass`

src/index.js, src/utils.js, test/sourceMap-options.test.js
loaders should generate absolute sources in source maps
No
No
=> fix: generate absolute sources for source maps

src/utils.js
check windows sources
No
No, maybe we should add more test in future
=> feat: improve `sources` checks

src/index.js, src/utils.js, test/__snapshots__/sourceMap-options.test.js.snap, test/sourceMap-options.test.js
fix source maps generation without the `sourceMap` option
No
No
=> fix: source maps generation

README.md, package-lock.json, package.json, src/utils.js, test/__snapshots__/implementation-option.test.js.snap
New projects with node-sass are returning an error due to latest being bumped to v5
`Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.`
Every new (or updated) project using node-sass latest version will result in compilation errors during to mismatch semver.
Supports >4.0.0, open to changes.
None
=> fix: support node-sass v5.0.0

README.md
The original size of Sass logo at readme is too small so two logos aren't centered.
No.
No.
=> docs: resize Sass logo

README.md
When installing node-sass, most of developer don't know that there is a little difference in using some features of sass between them.
[The Sass team discourages the continued use of the @import rule](https://sass-lang.com/documentation/at-rules/import) (it will be deprecated), and they suggest using @use rule instead, which is supported only by dart sass.
- [ x] **metadata update**
=> added important information about sass loader

.eslintrc.js, .github/workflows/nodejs.yml, README.md, package-lock.json, package.json, src/utils.js, test/additionalData-option.test.js, test/implementation-option.test.js, test/loader.test.js, test/sassOptions-option.test.js, test/sourceMap-options.test.js, test/validate-options.test.js, test/webpackImporter-options.test.js
Disabled `fiber` on node >= 16
No
No
=> fix: disabled fiber on node >= 16

CHANGELOG.md
Not sure why but the changelog doesn't contain at the moment info about `10.2.0`.
`10.2.0` is a published version on npm and there are even commits that mention that version:
https://github.com/webpack-contrib/sass-loader/compare/v10.1.1...v10.2.0
This PR just add information from the commit https://github.com/webpack-contrib/sass-loader/commit/05b848b8a36db9c7a88bbe201ed6c8b70927d309
=> Update CHANGELOG.md, add info about 10.2.0

.eslintrc.js, .github/workflows/nodejs.yml, README.md, package-lock.json, package.json, src/utils.js, test/additionalData-option.test.js, test/implementation-option.test.js, test/loader.test.js, test/sassOptions-option.test.js, test/sourceMap-options.test.js, test/validate-options.test.js, test/webpackImporter-options.test.js
Original Changes: 4ca004b
Backported the changes from 4ca004b to the 10.x line, so that projects stuck on Webpack 4 can still use Node v16.
There are unit test failures that seem unrelated to these changes, and the unit tests wouldn't run at all for me before them, so I'm unsure how to handle them.
Additionally, I'm not sure if the `v10` branch is the correct one, let me know if this needs to be against a different branch.
=> fix: backported disabled auto importing `fiber` on node >= 16

README.md
Use primitive types instead of object types in the readme 
Markdown preview link here: https://github.com/webpack-contrib/sass-loader/blob/a1cd3bfdf7a3ec2ab144b6fcb3f960db3bb9153c/README.md
=> docs(readme): update types

src/utils.js
Add sass-embedded to default implementations:
While using create-react-app and react-app-rewired I want to use sass-embedded, but config-overrides doesn`t work as expected: 
scssLoader.options.implementation = require('sass-embedded');
doesn`t apply, I`m getting errors like "sass not found". So the easiest way to fix this is to add sass-embedded to getDefaultSassImplementation function.
P.S. Idk if it is a bugfix or feature :D
=> Add sass-embedded to default implementations

src/SassError.js
refactor error code, no need to lose memory on original error
Yes, if you use original error, but I don't think somebody to use it
No
=> refactor: error code

README.md, commitlint.config.js, src/utils.js
docs: add impofration how to enable @debug output
- [x ] new **feature**
1. The debug message on each line is too long because the output contains an absolute file before self message.
Here was changed debug message formatting to:  [debug:line:column] message.
2. In readme is added "How to enable @debug output", because since sass-loader 1.12.0 the output of `@debug` is disabled  by default.
Details see in the [issue](https://github.com/webpack-contrib/sass-loader/issues/1065).
NO
=> feat: optimize debug message formatting, #1065

src/utils.js
https://github.com/webpack-contrib/sass-loader/pull/1002 was incomplete (I guess? because it wasn't working for me, and with this change it does).
With:
```
"node-sass": "^7.0.0",
"sass-loader": "^10.3.0",
```
Got error:
```
ERROR in ./app/app.global.scss (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/sass-loader/dist/cjs.js!./app/app.global.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Node Sass version 7.0.1 is incompatible with ^4.0.0 || ^5.0.0 || ^6.0.0.
@ ./app/app.global.scss 2:26-145 43:4-64:5 46:18-137
@ ./app/index.js
@ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.js
N
```
=> fix: add support for node-sass 7

src/utils.js, test/helpers/getCodeFromSass.js, test/loader.test.js, test/node_modules/package-with-exports-and-custom-condition/index.cjs, test/node_modules/package-with-exports-and-custom-condition/index.js, test/node_modules/package-with-exports-and-custom-condition/package.json, test/node_modules/package-with-exports-and-custom-condition/style-1.scss, test/node_modules/package-with-exports-and-custom-condition/style-2.scss, test/node_modules/package-with-exports/package.json, test/sass/import-package-with-exports-and-custom-condition.sass, test/scss/import-package-with-exports-and-custom-condition.scss
This allows consumers to set their own considitionNames and have sass pick this up.
Examples:
Supporting a single entrypoint but targeting multiple themes
```scss
@use 'my-design-tokens';
.class {
color: my-design-tokens.$color-1
}
```
package.json
```json
{
"name": "my-design-tokens",
"exports": {
".": {
"sass": {
"theme1": "./path-to-theme1.scss",
"theme2": "./path-to-theme2.scss"
}
}
}
}
```
Webpack config
```
module.exports = {
resolve: {
conditionNames: [someFlag ? "theme1" : "theme2", "..."]
}
}
```
=> feat: extend conditionNames

package-lock.json, package.json
bumps `node-sass` version to v8.0.0
Adds node-sass v8.0.0 to package.json
🤷 
Looks similar enough to https://github.com/webpack-contrib/sass-loader/commit/be5cbc9b5f851422bcead329d4bfb0c9dab5eb18 + `npm test` passed locally for me.
=> feat: add support for node-sass v8

src/utils.js
fixes https://github.com/webpack-contrib/sass-loader/issues/1101#issuecomment-1315426747
No
No
=> Fix compatibility node sass v8

src/SassError.js, src/index.js, src/utils.js, test/__snapshots__/implementation-option.test.js.snap
Part of https://github.com/webpack/webpack/issues/15980
No
No
=> fix: error handling

package.json, src/utils.js, test/helpers/getCodeFromSass.js, test/loader.test.js
Avoid using `klona` - better perf and less deps
No
fixes https://github.com/webpack-contrib/sass-loader/pull/1034
=> fix(perf): avoid using `klona` for `sass` options

src/utils.js
Don't load `neo-async` when it is unnecessary, not only `node-sass` can be used
No
No
=> refactor: load `neo-async` lazily

src/utils.js
When trying to update the sass engine from the legacy node-sass into the new ones we found that users using webpack v4 doesn't have the ability to use the new sass-embedded implementation as the sass-loader version that supports it doesn't work with webpack v4. This is a good addition because using the javascript sass only implementation has big performance penalties.
=> [v10] feat: support sass embedded

README.md
Add the missing parameter
None
None
=> docs: add missing parameter

src/utils.js
This is a small fix for what was introduced at https://github.com/webpack-contrib/sass-loader/pull/1152
I haven't realised before but we were missing the sass-embedded check at this place.
=> [v10] fix: missing sass embedded check when get default implementation

test/helpers/getCodeFromSass.js, test/loader.test.js, test/node_modules/webpack-export-field/dist/styles/file.css, test/node_modules/webpack-export-field/dist/styles/file.scss, test/node_modules/webpack-export-field/dist/styles/webpack/file.css, test/node_modules/webpack-export-field/dist/styles/webpack/file.scss, test/node_modules/webpack-export-field/package.json, test/sass/webpack-export-field.sass, test/scss/webpack-export-field.scss
fixes https://github.com/webpack-contrib/sass-loader/issues/1187
No
No
=> test: the `webpack` export field

src/utils.js, test/loader.test.js, test/node_modules/pkg/package.json, test/node_modules/pkg/styles/index.scss, test/sass/use-pkg.sass, test/scss/use-pkg.scss
Handle `pkg:` scheme inside webpack importer
No
No
=> fix: handle `pkg:` scheme

README.md, src/index.js, src/options.json, src/utils.js, test/__snapshots__/additionalData-option.test.js.snap, test/__snapshots__/implementation-option.test.js.snap, test/__snapshots__/sassOptions-option.test.js.snap, test/__snapshots__/sourceMap-options.test.js.snap, test/__snapshots__/validate-options.test.js.snap, test/__snapshots__/warnRuleAsWarning.test.js.snap, test/helpers/customFunctions.js, test/helpers/getCodeFromSass.js, test/helpers/getImplementationByName.js, test/helpers/getImplementationsAndAPI.js, test/implementation-option.test.js, test/loader.test.js, test/sassOptions-option.test.js, test/sourceMap-options.test.js, test/validate-options.test.js, test/webpackImporter-options.test.js
This implements the Shared Resources proposal that was accepted and implemented in Dart Sass 1.70.0. By reusing the same compiler process when compiling multiple files, this significantly improves performance for tools like webpack.
None
Closes: https://github.com/webpack-contrib/sass-loader/issues/1163
=> perf: reuse compiler process when using sass-embedded

README.md
add note about css and style loader also updated syntax of github note and warning.
No
No
=> docs: add note about css and style loader

README.md
These are a number of small grammar issues I noticed while working on #1211 which I figured I'd do a dedicated PR for - these are not Strictly Better and there are still some improvements that could be made, but they feel like a good start :)
This is not a breaking change
=> docs: improve the grammar of the readme

.github/workflows/nodejs.yml
It seems like there isn't a precompiled version of `node-sass` available for `macos-latest`, and `node-gpy` then fails to build it from source due to the version not [being compatible with Python 3.12](https://github.com/sass/node-sass/issues/3420).
It seems like [this might be the last straw](https://github.com/sass/node-sass/issues/3424) for `node-sass` but in the meantime we can work around this by just explicitly installing an older version of Python when running on `macos-latest`.
This is not a breaking change
=> ci: use a version of Python that `node-sass` can be built on for macOS

README.md, src/utils.js, test/__snapshots__/implementation-option.test.js.snap, test/implementation-option.test.js, test/validate-options.test.js
[The Sass team considers `sass-embedded` to be stable and production-ready](https://github.com/webpack-contrib/sass-loader/issues/1180#issuecomment-2237851483), so by preferring it over `sass` developers can use `optionalDependencies` to take advantage of the more performant variant whenever possible without having to explicitly determine that for themselves.
Resolves #1180
Resolves https://github.com/webpack-contrib/sass-loader/issues/1210
My understanding is that `sass-embedded` is a drop-in replacement, meaning this should not be a breaking change, though would appreciate input from @nex3 to confirm this is true enough to make this technically-not-breaking
=> perf: prefer `sass-embedded` if available

README.md
Fixes the incorrect `content` parameter in the documentation of the `sassOptions` function, closes #1226
=> fix: remove incorrect parameter documentation of `sassOptions` function

src/utils.js, test/__snapshots__/sourceMap-options.test.js.no-node-sass.snap, test/__snapshots__/sourceMap-options.test.js.snap, test/sass/language-source-maps.sass, test/scss/language-source-maps.scss, test/sourceMap-options.test.js
Generate correct sourceMaps when custom importer is used.
https://github.com/sass/sass/issues/3300
https://github.com/webpack-contrib/sass-loader/issues/1217
=> fix: generate correct sourceMaps when custom importer is used

package.json, src/utils.js, test/__snapshots__/implementation-option.test.js.no-node-sass.snap, test/__snapshots__/implementation-option.test.js.snap, test/implementation-option.test.js
idk how to cover this by tests
fixes #1244
No
No
=> fix(modern-compiler): dispose redundant compilers
